# .circleci/config.yml
version: 2.1
workflows:
  main:
    jobs:
      - release:
          # Only run this job on git tag pushes
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
        build:
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /.*/

jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.14



    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: make test
      - run: make build
  release:
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - run: echo "$docker_hub_pass" | docker login -u topine --password-stdin
      - run: curl -sL https://git.io/goreleaser | bash